CREATE DATABASE mediaTech;

USE mediaTech;

CREATE TABLE cadastro (
	cod int(5) NOT NULL auto_increment,
	usuario varchar(40) NOT NULL,
	senha varchar(20) NOT NULL,
	email varchar(60) NOT NULL UNIQUE,
	PRIMARY KEY(cod)
);

CREATE TABLE noticias(
	cod int(5) NOT NULL auto_increment,
	titulo text,
	conteudo mediumtext,
	data date,
	PRIMARY KEY(cod)
);

INSERT INTO noticias VALUES (default,'Inteligência artificial vai adivinhar quem lhe agrada mais no Tinder','Usando tecnologias de inteligência artificial, o Tinder inaugura um recurso chamado Super Likeable, que sugere aos usuários pessoas que provavelmente iriam agradá-los de acordo com o seu perfil no aplicativo. A ferramenta funciona assim: aleatoriamente, ao usar o Tinder, você vai se deparar com a tela do Super Likeable. Não adianta você procurar o recurso, é ele que vai encontrá-lo. Assim que aparecer, ele vai sugerir quatro pessoas que o sistema de inteligência artificial considera que vão agradá-lo. Nesse momento você também ganha um superlike para gastá-lo com uma das quatro sugestões feitas pelo app.Esse superlike que o usuário ganha especificamente para usar no Super Likeable – que é além do superlike diário que todos têm – só pode ser usado nesse momento, ou seja, se você não escolher umas das pessoas sugeridas, você vai perdê-lo. O novo recurso do Tinder já está sendo testado entre usuários de Nova York e de Los Angeles e ainda não tem data definida para estrear oficialmente em todos os aparelhos com o aplicativo.' , '2018-03-07'),
(default,'Como começar a usar o Quantum, a mais nova atualização do Firefox.','Firefox é um navegador desenvolvido pela Mozila, com a intenção de oferecer maior privacidade, segurança e rapidez para os usuários. Ele foi lançado em 2004 e desde então se tornou o terceiro mais utilizado no mundo todo, acessível para diversos sistemas operacionais, incluindo os mais famosos: Linux, macOS e Windows. A mais nova atualização do Firefox, o Firefox Quantum, vem com a promessa de ser 30% mais rápida que as anteriores, com melhorias em seu design, desempenho, funções e segurança. Ela foi desenvolvida para ler páginas mais rapidamente, priorizar abas em atividade, possuir uma biblioteca com sites favoritos, downloads e históricos, bloquear rastreadores e salvar links para serem acessados posteriormente de outros dispositivos. Para atualizar o navegador para o Firefox Quantum, basta permitir a atualização através de uma notificação que aparece ao iniciar ou ir em "Sobre o Navegador" e selecioná-la manualmente. Confira então 5 dicas para começar a usar o navegador Firefox Quantum.', '2018-03-07'),
(default,'Pagamento via SMS ou USSD','Os pagamentos via SMS ou mensagem de texto são oferecidos no Brasil pelas operadoras de celular, como o Oi Carteira, Zumm Vivo, Multibank Tim Caixa e Meu Dinheiro Claro. Como cada uma tem um sistema próprio, só é possível utilizar a solução da empresa com a qual o smartphone ou tablet foi habilitado – a principal diferença entre o pagamento via SMS e o via USSD é a ausência de consumo de crédito do celular gerado pelo envio de mensagem de texto no segundo caso. Ou seja, para que você receba e faça pagamentos com este tipo serviço, você vai precisar de um celular ou tablet compatível, uma das soluções acima, o app da empresa (gratuito) e conexão com a internet. Apesar de diversas operadoras terem firmado parceria com bancos e carteiras digitais para oferecer essa forma de pagamento, não é preciso ter conta com eles, pois é possível fazer o pagamento usando os créditos do celular ou através de cobrança na conta telefônica. Além disso, eles trazem ainda a opção de solicitar também um cartão de crédito ou de débito Visa ou Mastercard, a depender da empresa. Desta forma, essa solução vêm se tornando bastante popular entre aqueles que não podem ou não conseguem ter uma conta bancária, mas precisam fazer pagamento de contas e serviços. No entanto, os limites liberados para compra por meio de mensagem de texto são geralmente de valor baixo para evitar que o serviço seja usado em lavagem de dinheiro.', '2018-03-07'),
(default, 'Internet Banking', ' Provavelmente a modalidade de pagamento via celular mais popular no Brasil, a agência bancária móvel ou internet banking permite o pagamento de diversas contas por meio do débito em conta corrente ou pagamento de boletos. Essa opção é a preferida do público brasileiro, principalmente por conta da segurança inspirada pelo ambiente bancário. Os aplicativos de internet banking para smartphones e tablets já estão amplamente disponíveis tanto para Android quanto para iOS, e há sistemas disponíveis também para Windows Phone.', '2018-03-07'),
(default, 'Bitcoin cai antes de lançamento de contratos futuros', 'A moeda virtual Bitcoin, que atingiu US$ 1.203 no final do ano passado, agora está valendo pouco mais de 300 dólares, ou apenas um quarto do pico histórico. A cotação caiu significativamente na última semana, após uma série de notícias preocuparem pessoas que possuem recursos em Bitcoin, como uma declaração negativa do governo da Rússia sobre a moeda e a suspensão de saques por um dos principais sites de câmbio, o MtGox.Antes da noite da quarta-feira da semana passada (5), quando a Apple removeu da App Store o Blockchain, último aplicativo de Bitcoin que ainda restava na loja, usado por mais de 120 mil pessoas, um Bitcoin valia mais de 900 dólares. Quando a notícia se espalhou, iniciou-se um grande volume de transações e a moeda encerrou o dia seguinte cotada a US$ 831. Na última sexta-feira (7), o banco central russo declarou que oferecer serviços e produtos em troca de moedas virtuais poderia ser considerado envolvimento em operações suspeitas. A instituição ainda afirmou que o rublo é a única moeda oficial do país e que introduzir qualquer outra moeda, incluindo o Bitcoin, seria ilegal. No final de janeiro, a Rússia havia dito que o Bitcoin era altamente especulativo e corria grande risco de perder valor.', '2018-03-07'),
(default, 'Bill Gates e Steve Jobs: 10 anos depois, quem substituiria os dois gênios?','Pode parecer que foi ontem, mas 2007 já está bem distante da gente. Dez anos mais distante, para sermos mais exatos. Se na nossa vidinha cotidiana isso já representa uma bela passagem de tempo, no mundo da tecnologia uma década é tempo mais do que suficiente para que marcas e produtos surjam, conquistem o mercado e desapareçam como em um passe de mágica. Até os grandes figurões da área costumam mudar nesse tempo, e é exatamente disso que vamos falar hoje. Se olharmos dez anos para trás, vemos uma indústria tecnológica extremamente polarizada e centrada em dois executivos que, ao longo de uma carreira histórica, provaram que são gênios e visionários, cada um ao seu próprio modo. Sim, estamos introduzindo nomes que, bem, dispensam qualquer introdução: Bill Gates e Steve Jobs. Enquanto o criador dos Macs galgava uma crescente impressionante desde sua volta à Apple, o fundador da Microsoft tinha dado os primeiros passos para se afastar de vez do dia a dia da empresa – tocada por Steve Ballmer. Ambos foram amigos por um tempo. Depois, se tornaram inimigos. Por volta de 2007? Bem, nessa época eram concorrentes ferozes, mas que, pouco a pouco, começavam a se acertar e reconhecer as forças um do outro. E foi exatamente nesse cenário e nesse ano que a dupla fez uma aparição pública história, durante uma entrevista feita na conferência All Things Digital. Não foi a primeira vez que os dois foram vistos juntos em um palco, mas, com toda a certeza, foi a mais marcante e icônica.O papo mediado por Walt Mossberg e Kara Swisher trouxe discussões importantes sobre mercado, produtos, serviços e como personalidades fortes eram praticamente essenciais para carregar suas marcas adiante. Mais do que isso, no entanto, o painel simbolizava o encontro de duas forças gigantescas e que traziam para si o peso de toda uma indústria.', '2018-03-07'),
(default, 'Por trás da tecnologia que cria rostos digitais super-realistas no cinema', 'Efeitos visuais fazem parte da magia do cinema desde os primórdios da sétima arte, mas foi apenas nos últimos 30 anos que efeitos gerados por computador passaram a permear os principais filmes da indústria cinematográfica internacional. Com o que se chama no meio de CGI ("Computer-generated imagery", ou "imagens geradas por computador"), os cineastas passaram a quebrar as barreiras da realidade para trazer à vida dinossauros, dragões, batalhas intergalácticas e reinos de fantasia.Um dos gêneros que mais se beneficiou do avanço dessa tecnologia foi o de ficção-científica. "Blade Runner 2049", sequência do clássico de 1982 que chegou neste ano aos cinemas, é um dos exemplos mais recentes de CGI sendo usado em situações antes inimagináveis. Em certo momento do filme, um rosto do filme original surge na tela: a replicante Rachel, vivida em 1982 pela atriz Sean Young. A questão é que, 35 anos atrás, Sean tinha apenas 23 anos e, obviamente, em 2017, a atriz não tem mais a mesma aparência do filme original. Como colocá-la de volta no papel de um android que não envelhece? É aí que entrou o CGI. A equipe da MPC, empresa contratada para cuidar dos efeitos visuais de "Blade Runner 2049", recriou o rosto de Sean Young com 23 anos de idade digitalmente. O que vemos na tela, embora se pareça muito com um rosto real, é na verdade uma imagem gerada por computador. Essa tecnologia não é exatamente inédita. Em 2016, a ILM recriou digitalmente o rosto jovem da atriz Carrie Fisher em "Star Wars: Rogue One", e também trouxe de volta à vida as feições do ator Peter Cushing, intérprete do general Moff Tarkin no filme original de 1977. Ou seja, tudo indica que veremos mais dessa técnica em 2018.', '2018-03-07');

	